import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '@/styles/Home.module.scss'
import { FC } from 'react'
import PageWithLayout from '@/layout/page.layout'
import MainLayout from '@/layout/main.layout'
import { Oxygen, Poppins } from 'next/font/google'
import { useRouter } from 'next/router'
import Image from 'next/image'
import PageOne from '@/components/slider/page'
import Page2 from '@/components/slider/page2'
import Page3 from '@/components/slider/page3'
import Page4 from '@/components/slider/page4'
import Page5 from '@/components/slider/page5'
import Page6 from '@/components/slider/page6'
import Cookies from 'js-cookie'
import { gql, useQuery } from '@apollo/client'



const poppins = Poppins({
  weight: "500",
  subsets: [ "latin" ]
})

const oxygen = Oxygen({
  weight: "400",
  subsets: [ "latin" ]
})

const Home: FC = () => {
  const router = useRouter();

  const [ slider, setSlider ] = useState(1)


  useEffect(() => {
    const interval = setInterval(() => {
      setSlider(() => slider + 1)
      if (slider === 6) {
        setSlider(1)
      }
    }, 10000)


    return () => clearInterval(interval)
  })

  const [ cookies, setCookies ] = useState("")

  useEffect(() => {
    const token = Cookies.get("physio_token");
    if (token) {
      setCookies(token)
    }
  }, [ cookies ])



  const { loading, data } = useQuery(gql`query GetAllServices {
    getAllServices {
      services
      image
      descriptions
      servicesID
    }
  }`)

  if (loading) return <p>Loadding...</p>
  return (
    <>
      <Head>
        <title>Leonardo: Physical Therapy Rehabilitation Clinic</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <div className={styles.tagline}>
          <h2 className={poppins.className}>Reclaiming Movement, Restoring Life.</h2>
          {cookies ? <button onClick={() => router.push("/patient/appointment/facetoface")}>BOOK NOW</button> : <button onClick={() => router.push("/auth/login")}>BOOK NOW</button>}
          {
            slider === 1 ? <PageOne /> : null
          }
          {
            slider === 2 ? <Page2 /> : null
          }

          {
            slider === 3 ? <Page3 /> : null
          }

          {
            slider === 4 ? <Page4 /> : null
          }
          {
            slider === 5 ? <Page5 /> : null
          }
          {
            slider === 6 ? <Page6 /> : null
          }


        </div>
        <div className={styles.title}>
          <h2 className={poppins.className}>Services</h2>
        </div>
        <div className={styles.services}>
          {data.getAllServices.map(({ services, image, servicesID, descriptions }: { services: string, image: string, servicesID: string, descriptions: string }) => (
            <div key={servicesID} className={styles.card}>
              <div className={styles.imgbox}>
                <Image src={image} alt="physical therapy" fill style={{
                  objectFit: "cover",
                  objectPosition: "center",
                  imageResolution: "from-image"
                }} />
              </div>
              <div className={styles.content}>
                <h2 className={poppins.className}>{services}</h2>
                <p className={oxygen.className}>{descriptions}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

    </>
  )
}

(Home as PageWithLayout).layout = MainLayout
export default Home
